### ISSUE TITLE
run_aggregation.sh missing

### ISSUE THREAD

**Issue by fabacha** [encryptogroup/SAFEFL#1]
Hi,
I hope you are doing well.

I am trying to replicate your work but I couldn't find the run_aggregation.sh file referenced in main.py line 441 in the MPSPDZ folder.

Can you please point me to where I can get that.

Thank you

**Comment by Tobias512** [comment]
Hi,
I apologize for the delayed response.

The files you are looking for were not committed properly due to a wrong configuration of the _.gitignore_ file. I added the missing files to the repo and now everything should work correctly. 

The following six files were missing from the _mp-spdz_ folder that is now in the repository:
- mpspdz/run_aggregation.sh
- mpspdz/ExternalIO/client.py
- mpspdz/ExternalIO/domains.py
- mpspdz/ExternalIO/mpc_client.py
- mpspdz/Programs/Source/mpc_fedavg_server.mpc
- mpspdz/Programs/Source/mpc_fltrust_server.mpc

If you still have problems, feel free to contact us.

Kind Regards,
Tobias
